export CG_TargetCommand_f
code
proc CG_TargetCommand_f 0 0
endproc CG_TargetCommand_f 0 0
proc CG_SizeUp_f 0 0
endproc CG_SizeUp_f 0 0
proc CG_SizeDown_f 0 0
endproc CG_SizeDown_f 0 0
proc CG_Viewpos_f 0 0
endproc CG_Viewpos_f 0 0
proc CG_Viewaxis_f 0 0
endproc CG_Viewaxis_f 0 0
proc CG_ScoresDown_f 0 0
endproc CG_ScoresDown_f 0 0
proc CG_ScoresUp_f 0 0
endproc CG_ScoresUp_f 0 0
proc CG_scrollScoresDown_f 0 0
endproc CG_scrollScoresDown_f 0 0
proc CG_scrollScoresUp_f 0 0
endproc CG_scrollScoresUp_f 0 0
proc CG_AutoKickDown_f 0 0
endproc CG_AutoKickDown_f 0 0
proc CG_AutoKickUp_f 0 0
endproc CG_AutoKickUp_f 0 0
proc CG_AutoBackStabDown_f 0 0
endproc CG_AutoBackStabDown_f 0 0
proc CG_AutoBackStabUp_f 0 0
endproc CG_AutoBackStabUp_f 0 0
proc CG_AutoAimDown_f 0 0
endproc CG_AutoAimDown_f 0 0
proc CG_AutoAimUp_f 0 0
endproc CG_AutoAimUp_f 0 0
