export FX_RocketProjectileThink
code
proc FX_RocketProjectileThink 0 0
endproc FX_RocketProjectileThink 0 0
export FX_RocketHitWall
proc FX_RocketHitWall 0 0
endproc FX_RocketHitWall 0 0
export FX_RocketHitPlayer
proc FX_RocketHitPlayer 0 0
endproc FX_RocketHitPlayer 0 0
export FX_RocketAltProjectileThink
proc FX_RocketAltProjectileThink 0 0
endproc FX_RocketAltProjectileThink 0 0
import trap_AnyLanguage_ReadCharFromString_1_02
import trap_AnyLanguage_ReadCharFromString_1_04
import trap_G2API_SetBoneAnim
import trap_G2API_GetGLAName
import trap_G2API_SetBoneAngles
import trap_G2API_CollisionDetect
import trap_G2API_CleanGhoul2Models
import trap_G2API_RemoveGhoul2Model
import trap_G2API_HasGhoul2ModelOnIndex
import trap_G2API_DuplicateGhoul2Instance
import trap_G2API_CopySpecificGhoul2Model
import trap_G2API_CopyGhoul2Instance
import trap_G2API_SetBoltInfo
import trap_G2API_AddBolt
import trap_G2API_InitGhoul2Model
import trap_G2API_GetBoltMatrix_NoRecNoRot
import trap_CG_RegisterSharedMemory
import trap_G2API_SetNewOrigin
import trap_G2API_SetSurfaceOnOff
import trap_G2API_SetRootSurface
import trap_Language_UsesSpaces
import trap_Language_IsAsian
import MV_SetGameVersion
import trap_MVAPI_EnableSubmodelBypass
import CG_Cvar_Get_int
import trap_MVAPI_SetVirtualScreen
import trap_R_AddRefEntityToScene2
import trap_MVAPI_Print
import trap_MVAPI_SetVersion
import trap_FS_FLock
import trap_MVAPI_GetVersion
import trap_MVAPI_ControlFixes
import MVAPI_AfterInit
import MVAPI_Init
import coolApi_jkaVersion
import coolApi_dbVersion
import coolApi
import mvapi
import trap_GetTemporaryUserCommand
import trap_G2API_GiveMeVectorFromMatrix
import trap_G2API_GetBoltMatrix_NoReconstruct
import trap_G2API_GetBoltMatrix
import trap_G2_HaveWeGhoul2Models
import trap_G2_SetGhoul2ModelIndexes
import trap_G2_ListModelBones
import trap_G2_ListModelSurfaces
import FX_ForceDrained
import FX_BlasterWeaponHitPlayer
import FX_BlasterWeaponHitWall
import FX_BlasterAltFireThink
import FX_BlasterProjectileThink
import FX_BryarAltHitPlayer
import FX_BryarHitPlayer
import FX_BryarAltHitWall
import FX_BryarHitWall
import CG_Spark
import FX_TurretHitPlayer
import FX_TurretHitWall
import FX_TurretProjectileThink
import CG_NewParticleArea
import initparticles
import CG_GetStripEdString
import CG_ParticleExplosion
import CG_ParticleMisc
import CG_ParticleDust
import CG_ParticleSparks
import CG_ParticleBulletDebris
import CG_ParticleSnowFlurry
import CG_AddParticleShrapnel
import CG_ParticleSmoke
import CG_ParticleSnow
import CG_AddParticles
import CG_ClearParticles
import trap_ROFF_Purge_Ent
import trap_ROFF_Play
import trap_ROFF_Cache
import trap_ROFF_UpdateEntities
import trap_ROFF_Clean
import trap_SP_GetStringTextString
import trap_SP_Print
import trap_FX_AddSprite
import trap_FX_AddPrimitive
import trap_FX_AddBezier
import trap_FX_AddPoly
import trap_FX_AdjustTime
import trap_FX_FreeSystem
import trap_FX_InitSystem
import trap_FX_AddScheduledEffects
import trap_FX_PlayBoltedEffectID
import trap_FX_PlayEntityEffectID
import trap_FX_PlayEffectID
import trap_FX_PlaySimpleEffectID
import trap_FX_PlayEntityEffect
import trap_FX_PlayEffect
import trap_FX_PlaySimpleEffect
import trap_FX_RegisterEffect
import trap_R_inPVS
import trap_GetEntityToken
import trap_getCameraInfo
import trap_startCamera
import trap_loadCamera
import trap_SnapVector
import trap_CIN_SetExtents
import trap_CIN_DrawCinematic
import trap_CIN_RunCinematic
import trap_CIN_StopCinematic
import trap_CIN_PlayCinematic
import BG_CycleForce
import BG_ProperForceIndex
import BG_CycleInven
import trap_Key_GetKey
import trap_Key_SetCatcher
import trap_Key_GetCatcher
import trap_Key_IsDown
import trap_MemoryRemaining
import testPrintFloat
import testPrintInt
import trap_OpenUIMenu
import trap_SetClientTurnExtent
import trap_SetClientForceAngle
import trap_SetUserCmdValueExtended
import trap_SetUserCmdValue
import trap_GetUserCmd
import trap_GetCurrentCmdNumber
import trap_GetServerCommand
import trap_GetSnapshot
import trap_GetCurrentSnapshotNumber
import trap_GetGameState
import trap_GetGlconfig
import trap_FX_AddLine
import trap_R_GetBModelVerts
import trap_R_SetLightStyle
import trap_R_GetLightStyle
import trap_R_RemapShader
import trap_R_DrawRotatePic2
import trap_R_DrawRotatePic
import trap_R_LerpTag
import trap_R_ModelBounds
import trap_R_DrawStretchPic
import trap_R_SetColor
import trap_R_RenderScene
import trap_R_LightForPoint
import trap_R_AddLightToScene
import trap_R_AddPolysToScene
import trap_R_AddPolyToScene
import trap_R_AddRefEntityToScene
import trap_R_ClearScene
import trap_CG_COOL_API_GetFileList
import trap_CG_COOL_API_GetFileVersion
import trap_CG_COOL_API_AttachG2Model
import trap_CG_COOL_API_GetSurfaceRenderStatus
import trap_CG_COOL_API_SkinlessModel
import trap_CG_COOL_API_SetSkin
import trap_CG_COOL_API_GetLanguageName
import trap_CG_COOL_API_GetNumLanguages
import CG_COOL_API_DB_GetMoreResults
import CG_COOL_API_DB_PreparedBindNull
import CG_COOL_API_DB_GetBinary
import CG_COOL_API_DB_FinishAndSendPreparedStatement
import CG_COOL_API_DB_PreparedBindBinary
import CG_COOL_API_DB_PreparedBindInt
import CG_COOL_API_DB_PreparedBindFloat
import CG_COOL_API_DB_PreparedBindString
import CG_COOL_API_DB_AddPreparedStatement
import CG_COOL_API_DB_GetString
import CG_COOL_API_DB_GetFloat
import CG_COOL_API_DB_GetInt
import CG_COOL_API_DB_NextRow
import CG_COOL_API_DB_GetReference
import CG_COOL_API_DB_NextResponse
import CG_COOL_API_DB_AddRequestTyped
import CG_COOL_API_DB_AddRequest
import CG_COOL_API_DB_EscapeString
import trap_CG_COOL_API_SetUserAngles
import trap_CG_COOL_API_GlResolutionChanged
import trap_CG_COOL_API_GetTimeSinceSnapReceived
import trap_CG_COOL_API_SetEzDemoBuffer
import trap_CG_COOL_API_SetPredictedMovement
import trap_R_Font_DrawString
import trap_R_Font_HeightPixels
import trap_R_Font_StrLenChars
import trap_R_Font_StrLenPixels
import trap_R_RegisterFont
import trap_R_RegisterShaderNoMip
import trap_R_RegisterShader
import trap_R_RegisterSkin
import trap_R_RegisterModel
import trap_R_LoadWorldMap
import trap_RealTime
import trap_S_StopBackgroundTrack
import trap_S_StartBackgroundTrack
import trap_S_RegisterSound
import trap_S_Respatialize
import trap_S_UpdateEntityPosition
import trap_S_AddRealLoopingSound
import trap_S_AddLoopingSound
import trap_S_ClearLoopingSounds
import trap_S_StartLocalSound
import trap_S_StopLoopingSound
import trap_S_StartSound
import trap_S_MuteSound
import trap_CM_MarkFragments
import trap_CM_TransformedBoxTrace
import trap_CM_BoxTrace
import trap_CM_TransformedPointContents
import trap_CM_PointContents
import trap_CM_TempBoxModel
import trap_CM_InlineModel
import trap_CM_NumInlineModels
import trap_CM_LoadMap
import trap_UpdateScreen
import trap_SendClientCommand
import trap_CG_COOL_API_AddMemeCommand
import trap_AddCommand
import trap_SendConsoleCommand
import trap_FS_FCloseFile
import trap_FS_Write
import trap_FS_Read
import trap_FS_FOpenFile
import trap_Args
import trap_Argv
import trap_Argc
import trap_Cvar_VariableStringBuffer
import trap_Cvar_Set
import trap_Cvar_Update
import trap_Cvar_Register
import trap_Milliseconds
import trap_Error
import trap_Print
import CG_SagaObjectiveCompleted
import CG_SagaRoundOver
import CG_InitSagaMode
import CG_CheckChangedPredictableEvents
import CG_TransitionPlayerState
import CG_Respawn
import CG_IsMindTricked
import CG_UpdateConfigString
import CG_PlayBufferedVoiceChats
import CG_VoiceChatLocal
import CG_LoadVoiceChats
import CG_ExecuteNewServerCommands
import CG_InitConsoleCommands
import CG_ConsoleCommand
import CG_DrawOldTourneyScoreboard
import CG_DrawOldScoreboard
import CG_DrawInformation
import CG_LoadingClient
import CG_LoadingItem
import CG_LoadingString
import CG_ProcessSnapshots
import CG_InitGlass
import CG_TestLine
import CG_SurfaceExplosion
import CG_MakeExplosion
import CG_Bleed
import CG_ScorePlum
import CG_CreateDebris
import CG_GlassShatter
import CG_BubbleTrail
import CG_SmokePuff
import CG_AddLocalEntities
import CG_AllocLocalEntity
import CG_InitLocalEntities
import CG_ImpactMark
import CG_AddMarks
import CG_InitMarkPolys
import CG_OutOfAmmoChange
import CG_DrawIconBackground
import CG_DrawWeaponSelect
import CG_AddPlayerWeapon
import CG_AddViewWeapon
import CG_MissileHitPlayer
import CG_MissileHitWall
import CG_FireWeapon
import CG_RegisterItemVisuals
import CG_RegisterWeapon
import CG_Weapon_f
import CG_PrevWeapon_f
import CG_NextWeapon_f
import CG_GetClientWeaponMuzzleBoltPoint
import TurretClientRun
import ScaleModelAxis
import CG_PositionRotatedEntityOnTag
import CG_PositionEntityOnTag
import CG_AdjustPositionForMover
import CG_Beam
import CG_ManualEntityRender
import CG_AddPacketEntities
import CG_SetEntitySoundPosition
import CG_ReattachLimb
import CG_UpdateForceActivationPredict
import CG_RegisterDirectHit
import CG_PainEvent_UpdatePredict
import CG_PainEvent
import CG_EntityEvent
import CG_PlaceString
import CG_CheckEvents
import CG_LoadDeferredPlayers
import CG_PredictPlayerState
import CG_RawTraceQ2Style
import CG_RawTrace
import CG_TraceQ2StyleLite
import CG_TraceQ2Style
import CG_Trace
import CG_PointContents
import CG_BuildSolidList
import CG_GetRootSurfNameWithVariant
import CG_PlayerShieldHit
import CG_CustomSound
import CG_NewClientInfo
import CG_AddRefEntityWithPowerups
import CG_ResetPlayerEntity
import CG_Player
import CG_StatusHandle
import CG_GetFlagCarrier
import CG_OtherTeamHasFlag
import CG_YourTeamHasFlag
import CG_GameTypeString
import CG_CheckOrderPending
import CG_Draw3DModel
import CG_GetKillerText
import CG_GetGameStatusText
import CG_GetTeamColor
import CG_InitTeamChat
import CG_SetPrintString
import CG_ShowResponseHead
import CG_DeferMenuScript
import CG_RunMenuScript
import CG_OwnerDrawVisible
import CG_GetValue
import CG_SelectNextPlayer
import CG_SelectPrevPlayer
import CG_Text_Height
import CG_Text_Width
import CG_Text_Paint
import CG_OwnerDraw
import CG_DrawTeamBackground
import CG_DrawFlagModel
import CG_DrawActive
import CG_DrawHead
import CG_CenterPrintMultiKill
import CG_CenterPrint
import CG_AddSpeed
import CG_AddLagometerSnapshotInfo
import CG_AddLagometerFrameInfo
import teamChat2
import teamChat1
import systemChat
import drawTeamOverlayModificationCount
import numSortedTeamPlayers
import sortedTeamPlayers
import CG_DrawPlayerInfoIcons
import CG_DrawPlayerName
import CG_DrawPlayerInfo
import CG_DrawTopBottom
import CG_DrawSides
import CG_DrawRect
import UI_DrawScaledProportionalString
import UI_DrawProportionalString
import CG_GetColorForHealth
import CG_ColorForHealth
import CG_TileClear
import CG_TeamColor
import CG_FadeColor
import CG_DrawStrlen
import CG_DrawSmallStringColor
import CG_DrawSmallString
import CG_DrawBigStringColor
import CG_DrawBigString
import CG_DrawStringExt
import CG_DrawNumField
import CG_DrawRotatePic2
import CG_DrawRotatePic
import CG_DrawPic
import CG_FillRect
import CG_DrawActiveFrame
import CG_AddBufferedSound
import CG_ZoomUp_f
import CG_ZoomDown_f
import CG_TestModelPrevSkin_f
import CG_TestModelNextSkin_f
import CG_TestModelPrevFrame_f
import CG_TestModelNextFrame_f
import CG_TestGun_f
import CG_TestModel_f
import CG_ForceModelChange
import CG_UpdateHud
import CG_WideScreenMode
import MV_UpdateCgFlags
import MV_LoadSettings
import CG_PrevForcePower_f
import CG_NextForcePower_f
import CG_PrevInventory_f
import CG_NextInventory_f
import CG_BuildSpectatorString
import CG_SetScoreSelection
import CG_RankRunFrame
import CG_EventHandling
import CG_MouseEvent
import CG_KeyEvent
import CG_LoadMenus
import CG_LastAttacker
import CG_CrosshairPlayer
import CG_ClearUnsetSystemInfoCvars
import CG_UpdateCvars
import CG_StartMusic
import CG_SendConsoleCommand
import CG_Error
import CG_DPrintf
import CG_Printf
import CG_Argv
import CG_ConfigString
import cg_randomTaunts
import cg_teleportEvents
import cg_cropLevelShot
import cg_drawLocalTimeSeconds
import cg_drawLocalTime12h
import cg_drawLocalTimeScale
import cg_drawLocalTimeY
import cg_drawLocalTimeX
import cg_drawLocalTime
import cg_char_color_blue
import cg_char_color_green
import cg_char_color_red
import cg_debugBB
import cg_snapHudFps
import cg_snapHudSpeed
import cg_snapHudDef
import cg_snapHudAuto
import cg_snapHudHeight
import cg_snapHudY
import cg_snapHudRgba2
import cg_snapHudRgba1
import cg_snapHud
import cg_smoothCameraFPS
import cg_smoothCamera
import cg_developer
import cg_drawPlayerSprites
import cg_mv_fixbrokenmodelsclient
import cg_com_physicsFps
import cg_com_maxfps
import cg_ui_myteam
import cg_recordSPDemoName
import cg_recordSPDemo
import cg_singlePlayerActive
import cg_enableBreath
import cg_enableDust
import cg_singlePlayer
import cg_currentSelectedPlayerName
import cg_currentSelectedPlayer
import cg_blueTeamName
import cg_redTeamName
import cg_trueLightning
import cg_noProjectileTrail
import cg_noTaunt
import cg_bigFont
import cg_smallFont
import cg_cameraMode
import cg_timescale
import cg_timescaleFadeSpeed
import cg_timescaleFadeEnd
import cg_cameraOrbitDelay
import cg_cameraOrbit
import cg_pmove_float
import cg_pmove_msec
import cg_pmove_fixed
import cg_smoothClients
import cg_consoleHudOffsetY
import cg_consoleHudOffsetX
import cg_hudFiles
import cg_scorePlum
import cg_noVoiceText
import cg_noVoiceChats
import cg_teamChatsOnly
import cg_drawFriend
import cg_deferPlayersDebug
import cg_deferPlayers
import cg_predictItems
import cg_blood
import cg_paused
import cg_buildScript
import cg_forceMySaber
import cg_forceMyModel
import cg_forceModel
import cg_stats
import cg_teamChatHeight
import cg_teamChatTime
import cg_debugMove
import cg_synchronousClients
import cg_strafebotSlopeHandling
import cg_cl_timeNudgeSafeServerTime
import cg_cl_timeNudgeAntiLagHack
import cg_g_unlockRandom
import cg_q2Skims
import cg_q2trace
import cg_mapDefaultRunFlags
import cg_mapDefaultJump
import cg_mapDefaultMsec
import cg_leadSoundsRace
import cg_leadSounds
import cg_strafebotFactor
import cg_drawEnemyInfo
import cg_lagometer
import cg_stereoSeparation
import cg_thirdPersonHorzOffset
import cg_thirdPersonAlpha
import cg_thirdPersonTargetDamp
import cg_thirdPersonCameraDamp
import cg_thirdPersonVertOffset
import cg_thirdPersonPitchOffset
import cg_thirdPersonAngle
import cg_thirdPersonRange
import cg_thirdPerson
import cg_backSwingCameraRange
import cg_lowhpsound
import cg_drawDemoName
import cg_drawPowerUpIcons
import cg_drawScoreboardIcons
import cg_colorScoreboard
import cg_smallScoreboard
import cg_drawInventory
import cg_SPRunAnim
import cg_fixlean
import cl_commandsize
import cg_fkSecondJumpDelay
import cg_fkFirstJumpDuration
import cg_fkDuration
import cg_fovViewmodelAdjust
import cg_fovViewmodel
import cg_fovAspectAdjust
import cg_widescreen
import cg_autoKillWhenFalling
import cg_remaps
import cg_saberTeamColors
import cg_teamRespawnShield
import cg_privateDuelShell
import cg_playerLOD
import cg_drawHitBox
import cg_brightskins
import cg_drawNonDuelers
import cg_thirdPersonFlagAlpha
import cg_newSaberHitSounds
import cg_hitSounds
import cg_rollSounds
import cg_jumpSounds
import cg_newFont
import cg_cleanChatbox
import cg_chatSounds
import cg_chatBoxCutOffLength
import cg_chatBoxX
import cg_chatBoxShowHistory
import cg_chatBoxHeight
import cg_chatBoxFontSize
import cg_chatBox
import cg_centerSize
import cg_centerHeight
import cg_drawScoreDefrag
import cg_drawScore
import cg_hudColors
import cg_movementKeysOnlySpec
import cg_movementKeysSize
import cg_movementKeysY
import cg_movementKeysX
import cg_movementKeys
import cg_drawTimerMsec
import cg_enhancedFlagStatus
import cg_crosshairIdentifyTarget
import cg_crosshairColor
import cg_crosshairSaberStyleColor
import cg_crosshairSizeScale
import cg_strafeHelper_RealPhysicsLines
import cg_strafeHelper_FPS
import cg_strafeHelperOffset
import cg_realAccelPreFriction
import cg_realAccelSlopes
import cg_realAccelDynScale
import cg_realAccelScale
import cg_realAccelNegativeColor
import cg_realAccelPositiveColor
import cg_strafeHelperInactiveAlpha
import cg_strafeHelperActiveColor
import cg_strafeHelperLineWidth
import cg_strafeHelperPrecision
import cg_strafeHelper
import cg_strafeHelperCutoff
import cg_customizeRace
import cg_forceFieldOpacityRace
import cg_forceFieldOpacity
import cg_forceMeterJumpCharge
import cg_forcemeterY
import cg_forcemeterX
import cg_forcemeter
import cg_showpos
import cg_speedometerSize
import cg_speedometerY
import cg_speedometerX
import cg_speedometer
import cg_raceTimerY
import cg_raceTimerX
import cg_raceTimerNoSpeeds
import cg_raceTimerSize
import cg_raceTimer
import cg_dismember
import cg_animBlend
import cg_auraShell
import cg_speedTrailSP
import cg_speedTrail
import cg_duelHeadAngles
import cg_saberEndsGlow
import cg_saberTrail
import cg_saberContact
import cg_saberDynamicMarkTime
import cg_saberDynamicMarks
import cg_fpls
import cg_saberModelTraceEffect
import cg_oldPainSounds
import cg_swingAngles
import cg_zoomFov
import cg_fov
import cg_simpleItems
import cg_ignore
import cg_autoswitch
import cg_tracerLength
import cg_tracerWidth
import cg_tracerChance
import cg_viewsize
import cg_drawGun
import cg_gun_z
import cg_gun_y
import cg_gun_x
import cg_gun_frame
import cg_addMarks
import cg_footsteps
import cg_showmiss
import cg_noPlayerAnims
import cg_specialPredictPhysicsFpsAngleCmdTime
import cg_specialPredictPhysicsFps
import cg_nopredict
import cg_errorDecay
import cg_debugRank
import cg_debugSaber
import cg_debugEvents
import cg_debugPosition
import cg_debugAnim
import cg_animSpeed
import cg_drawStrafeHelperSpeedometerAlways
import cg_drawCenterAlways
import cg_draw2D
import cg_antiLoopIndicatorY
import cg_antiLoopIndicatorX
import cg_drawAntiLoopIndicator
import cg_drawStatus
import cg_crosshairHealth
import cg_crosshairSize
import cg_crosshairY
import cg_crosshairX
import cg_teamOverlayUserinfo
import cg_drawTeamOverlay
import cg_drawRewards
import cg_dynamicCrosshair
import cg_drawScores
import cg_drawCrosshairNamesDetails
import cg_drawCrosshairNames
import cg_drawCrosshair
import cg_drawAmmoWarning
import cg_drawIcons
import cg_draw3dIcons
import cg_drawSnapshot
import cg_drawStrafeBotFactor
import cg_drawFPSLowest
import cg_drawFPSPhysical
import cg_drawFPSSamples
import cg_drawFPSMisses
import cg_drawFPSShorterCheckSim
import cg_drawFPS
import cg_drawRamps
import cg_drawTimer
import cg_shadows
import cg_bobroll
import cg_bobpitch
import cg_bobup
import cg_runroll
import cg_runpitch
import cg_centertime
import cg_autoKick_leadFactor
import cg_advancedPrediction
import cg_autoBackStab_leadAdjust
import cg_autoAim_retargetInterval
import cg_autoAim_maxLeadMs
import cg_autoAim_leadFactor
import cg_passiveAimAssist_width
import cg_passiveAimAssist_range
import cg_passiveAimAssist
import cg_autoAim_smoothFactor
import cg_autoAim_smooth
import cg_autoAim_switchDelay
import cg_autoAim_fov
import cg_autoAim_ignoreWalls
import cg_autoAim_usePrediction
import cg_v24tracing
import cg_autoAim_debug
import cg_autoAim
import cg_friendsChatsOnly
import cg_showKills
import cg_drawKillMessage
import cg_debugSaberBox_usePrediction
import cg_debugSaberBox
import cg_autoBackStab_trackTime
import cg_autoBackStab_track
import cg_autoBackStab_crouch
import cg_autoBackStab_cooldown
import cg_autoBackStab_maxAngle
import cg_autoBackStab_usePrediction
import cg_autoBackStab_distance
import cg_autoBackStab_debug
import cg_autoBackStab
import cg_autoKick_minVelocityZ
import cg_autoKick_minWallNormal
import cg_autoKick_cooldown
import cg_autoKick_checkKnockdown
import cg_autoKick_checkAir
import cg_autoKick_checkRoll
import cg_autoKick_indicator
import cg_autoKick_usePrediction
import cg_autoKick_distance
import cg_autoKick_sideKickFirst
import cg_autoKick_debug
import cg_autoKick
import cg_playerInfo
import cg_wallHack_iconOffsetZ
import cg_wallHack_iconScale
import cg_wallHack_showIcons
import cg_wallHack_showInfo
import cg_wallHack_showBoxes
import cg_wallHack_showNames
import cg_espShowStance
import cg_espItems
import cg_espEnemyColor
import cg_espFriendColor
import cg_espShowPowerups
import cg_espShowForce
import cg_espShowDistance
import cg_espShowBar
import cg_espShowHealth
import cg_espScale
import cg_espMaxDist
import cg_esp
import cg_friendPersistMaxPing
import cg_friendPersistStrictModel
import cg_friendPersist
import cg_enemyMarker
import cg_friendMarker
import cg_enemyList
import cg_friendList
import cg_wallHack
import cg_teleportDisable
import cg_markPolys
import cg_items
import cg_weapons
import cg_entities
import cg
import cgs
import CGCam_SetMusicMult
import CGCam_Shake
import cgScreenEffects
import ammoTicPos
import forceTicPos
import cg_statsEntities
import dueltypes
import angleVectors
import BG_Cmd_TokenizeString
import BG_Cmd_DropArg
import BG_Cmd_ArgsBuffer
import BG_Cmd_Cmd
import BG_Cmd_ArgsFrom
import BG_Cmd_Args
import BG_Cmd_Argv
import BG_Cmd_Argc
import Key_GetProtocolKey15
import Key_GetProtocolKey
import MV_SetGamePlay
import MV_BuildAnimationMappingTable
import animMappingTable_1_02_to_1_04
import animMappingTable_1_04_to_1_02
import jk2startversion
import jk2gameplay
import jk2version
import BG_DB_VerifyPassword
import g_arenaInfosHashed
import g_numArenas
import forcePowerDarkLight
import WeaponAttackAnim
import WeaponReadyAnim
import WP_SetSaber
import BG_SI_DeactivateTrail
import BG_SI_ActivateTrail
import BG_SI_LengthMax
import BG_SI_Length
import BG_SI_SetLengthGradual
import BG_SI_SetDesiredLength
import BG_SI_SetLength
import BG_SI_Active
import BG_SI_BladeActivate
import BG_SI_Deactivate
import BG_SI_Activate
import BG_BLADE_DeactivateTrail
import BG_BLADE_ActivateTrail
import BG_OutOfMemory
import BG_StringAlloc
import BG_TempFree
import BG_TempAllocTry
import BG_TempAlloc
import BG_AllocUnaligned
import BG_Alloc
import BG_CanUseFPNow
import BG_HasYsalamiri
import BG_GetItemIndexByTag
import BG_ParseAnimationFile
import BG_PlayerTouchesItem
import BG_PlayerStateToEntityStateExtraPolate
import BG_PlayerStateToEntityState
import BG_TouchJumpPadVelocity
import BG_TouchJumpPad
import BG_StatsToRaceStyle
import BG_RaceStyleToUserStats
import BG_StatsToUserCmd
import BG_UserCmdToUserStats
import BG_AddPredictableEventToPlayerstate
import BG_EvaluateTrajectoryDelta
import BG_EvaluateTrajectory
import BG_ForcePowerDrain
import BG_SaberStartTransAnim
import BG_InDeathAnim
import BG_InRoll
import BG_KnockawayForParry
import BG_BrokenParryForParry
import BG_BrokenParryForAttack
import BG_SaberInSpecialAttack
import BG_SpinningSaberAnim
import BG_FlippingAnim
import BG_SaberInIdle
import BG_SaberInSpecial
import BG_SaberInAttack
import BG_DirectFlippingAnim
import BG_InBackFlip
import BG_InReboundRelease
import BG_InReboundHold
import BG_InReboundJump
import BG_InSaberStandAnim
import BG_InSpecialJump
import BG_LegalizedForcePowers
import saberMoveData
import BG_CanItemBeGrabbed
import BG_FindItemForHoldable
import BG_FindItemForPowerup
import BG_FindItemForWeapon
import BG_FindItem
import vectoyaw
import bg_numItems
import bg_itemlist
import Pmove
import PM_UpdateViewAngles
import pm
import bgForcePowerCost
import forceMasteryPoints
import forceMasteryLevels
import bgAllAnims
import bgGlobalAnimations
import BGPAFtextLoaded
import forcePowerSorted
import WP_MuzzlePoint
import InitFpsTable
import fpsTableIndexToMsec
import fpsTableMsecToIndex
import DF_AntiLoop_NewAngle
import DF_DemoRaceStyleNamePart
import miniva
import multiva
import getDefaultMapRaceStyle
import getLeaderboardSQLConditions
import classifyLeaderBoard
import RaceStyleIsMainLeaderboard
import RunFlagsToString
import DF_MsToString
import MovementIsQuake3Based
import MovementStyleHasCPMOnlyJumppads
import MovementStyleHasVQ3OnlyJumppads
import MovementStyleHasQuake2Ramps
import LeaderboardNameToInteger
import RaceNameToInteger
import PlayerModeNameToInteger
import defaultRaceStyle
import leaderboardNames
import moveStyleNames
import modeNames
import runFlagsVeryShortNames
import runFlagsShortNames
import runFlagsNames
import MAX_RUN_FLAGS
import allowedMovementStyles
import allowedMapDefaultRunFlags
import allowedRunFlags
import allowedRollRunFlags
import defaultRunFlags
import ammoData
import weaponData
import weaponData_1_04
import weaponData_1_03
import weaponData_1_02
import clampedIntAdd
import clampedIntMult
import parseHex
import colorToHex
import safeatoi
import sanitizeFilename
import GetStringForID
import GetIDForString
import Q_irandExpectedIf
import Q_irand
import irand
import flrand
import Rand_Init
import Com_Printf
import Com_Error
import Info_NextPair
import Info_Validate
import Info_SetValueForKey_Big
import Info_SetValueForKey
import Info_RemoveKey_big
import Info_RemoveKey
import Info_HasKey
import Info_ValueForKey
import va
import FloatSwap
import LongSwap
import ShortSwap
import Q_StripColor
import Q_strstrip
import Q_strchrs
import Q_CleanAsciiStr
import Q_CleanStr
import Q_PrintStrlen
import Q_strcat
import Q_strnncpyz
import Q_strncpyz
import Q_strrchr
import Q_strupr
import Q_strlwr
import Q_stricmpn
import Q_strncmp
import Q_stricmp
import Q_isalpha
import Q_isupper
import Q_islower
import Q_isprint
import Com_sprintf
import Parse3DMatrix
import Parse2DMatrix
import Parse1DMatrix
import SkipRestOfLine
import SkipBracedSection
import COM_MatchToken
import COM_ParseVec4
import COM_ParseFloat
import COM_ParseInt
import COM_ParseString
import COM_ParseWarning
import COM_ParseError
import COM_Compress
import COM_ParseExt
import COM_Parse
import SkipWhitespace
import COM_GetCurrentParseLine
import COM_BeginParseSession
import COM_DefaultExtension
import COM_StripExtension
import COM_SkipPath
import Com_Clampi
import Com_Clamp
import PerpendicularVector
import AngleVectors
import MatrixMultiply
import MakeNormalVectors
import RotateAroundDirection
import RotatePointAroundVector
import ProjectPointOnPlane
import PlaneFromPoints
import AngleDelta
import AngleNormalize180
import AngleNormalize360
import AnglesSubtract
import AngleSubtract
import LerpAngle
import AngleMod
import BoxOnPlaneSide
import SetPlaneSignbits
import AxisCopy
import AxisClear
import AnglesToAxis
import vectoangles
import Q_crandom
import Q_random
import Q_rand
import ET_asin
import Q_acos
import Q_log2
import VectorRotate
import Vector4Scale
import VectorNormalize2
import VectorNormalize
import CrossProduct
import VectorInverse
import VectorNormalizeFast
import DistanceSquared
import Distance
import VectorLengthSquared
import VectorLength
import VectorCompare
import AddPointToBounds
import ClearBounds
import RadiusFromBounds
import NormalizeColor
import ColorBytes4
import ColorBytes3
import _VectorMA
import _VectorScale
import _VectorCopy
import _VectorAdd
import _VectorSubtract
import _DotProduct
import ByteToDir
import DirToByte
import Q_pown
import JK2_powf
import ClampShort
import ClampChar
import floatint
import intfloat
import Q_rsqrt
import Q_fabs
import axisDefault
import vec3_origin
import g_color_table_nt
import g_color_table
import colorDkBlue
import colorLtBlue
import colorDkGrey
import colorMdGrey
import colorLtGrey
import colorWhite
import colorCyan
import colorMagenta
import colorYellow
import colorBlue
import colorGreen
import colorRed
import colorBlack
import colorTable
import bytedirs
import Hunk_Alloc
import forceSpeedLevels
import bsearch
import copysignf
import powf
import logf
import expf
import frexpf
import roundf
import asin
import acos
import fabs
import abs
import tan
import atan2
import cos
import sin
import sqrt
import floor
import ceil
import memcmp
import memcpy
import memset
import memmove
import sscanf
import vsnprintf
import _atoi
import atoi
import _atof
import atof
import toupper
import tolower
import strncpy
import strstr
import strchr
import strcmp
import strcpy
import strcat
import strlen
import rand
import srand
import qsort
